const mongoose = require('mongoose');

const notesma = new mongoose.Schema({
    noteId: mongoose.Schema.Types.ObjectId, // Automatically generated by MongoDB
    bookId: String,
    content: String,
  }, );
  
  const NoteSchema= new mongoose.Schema({
    uid: String, // Unique identifier for the user
    notes: [notesma], // Array of notes
  }, { timestamps: true });
  
  
  module.exports = mongoose.model('Note', NoteSchema);